#!/bin/bash  ---> shebang 
statement you should inform linux server how to execute the script if you dont give it will not work it is used how to compile and how to execute

echo "hello world im learing"  --> it is used to print some thing
bash = shell
sh script name
bash and shell both are same
variable
data types
conditions
loops
functions

variables:
dry run: dont repeat yourself when ever there is a duplicate try to avoid it 
1.declaring inside the script
2.how to execute a command inside shell script and take the output

